# Generated by Django 4.2.7 on 2023-11-22 19:27

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Опиис'),
        ),
    ]
