# Generated by Django 4.2.7 on 2023-11-22 20:11

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_email_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='имя товару')),
                ('description', djrichtextfield.models.RichTextField(blank=True, verbose_name='Опиис')),
                ('activate', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='имя товару'),
        ),
    ]
