# Generated by Django 4.2.7 on 2023-11-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price_opt',
            field=models.IntegerField(default=0, verbose_name='Opt'),
        ),
    ]
